env:
  node: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
root: true

rules:
  # 要求语句末尾使用分号
  semi: [ "error", "always" ]
  "@typescript-eslint/semi": "off"
  # 强制使用一致的引号风格 废弃
  "@typescript-eslint/quotes": off
  no-unused-vars: "off"
  accessor-pairs: "off"
  "@typescript-eslint/indent":
    - off
    - 4
    - SwitchCase: 1
      ignoredNodes:
        - Decorators
        - PropertyDefinition

  "@typescript-eslint/prefer-nullish-coalescing": [ "off" ]
  "@typescript-eslint/strict-boolean-expressions": [ "off" ]
  "@typescript-eslint/explicit-function-return-type": "off"
  "n/no-path-concat": "off"
  "@typescript-eslint/no-extraneous-class": "off"
  "@typescript-eslint/no-empty-interface": "off"
  "@typescript-eslint/method-signature-style": "off"
  "@typescript-eslint/no-this-alias": "off"
  "@typescript-eslint/no-unused-vars": "off"
  "@typescript-eslint/no-namespace": "off"
  no-throw-literal: "off"
  "@typescript-eslint/no-throw-literal": "off"
  "@typescript-eslint/restrict-template-expressions": "off"
  "@typescript-eslint/no-var-requires": "off"
  "@typescript-eslint/member-delimiter-style":
    - error
    - multiline:
        delimiter: semi
        requireLast: true
      singleline:
        delimiter: semi
        requireLast: false
  "@typescript-eslint/ban-types": "off"
  "@typescript-eslint/naming-convention": "off"
  "@typescript-eslint/no-empty-function": "off"
  "@typescript-eslint/no-explicit-any": "off"
  "prefer-rest-params": "off"
  "prefer-spread": "off"
